### ISSUE TITLE
some of the buttons do nothing

### ISSUE THREAD

**Issue by jeisner** [Mimieam/TabSorter2#18] opened 2019-04-07 17:28 UTC
Some of the buttons work as advertised, but many of them seem to have no effect.  
Am I the first to report this?  Is there any information I can provide that will help you fix it?

(Note: I'm using Linux, but I'm not sure how that would explain the pattern of non-functionality.)

**Comment by Mimieam** [comment] 2019-04-23 02:54
Hi @jeisner, using linux shouldn't affect the functionalities. There is a known chrome bug with getting the current window id, I'm writing a workaround and will push it in the next release :)

**Comment by nstielau** [comment] 2019-06-26 16:45
Great tool!  I'm on Fedora 29.  For me, the Options and Deduplicate Current do not work.

**Comment by Mimieam** [comment] 2019-11-09 02:31
Ok So this took much longer than anticipated to reproduce and figure out what was going on here. I primarily developed this app on a laptop with 1 monitor. so this chrome bug was never noticed.

So it turns out, that those buttons actually works - that is the JS behind is correctly triggered - but the css animation does not and this seems to be linked to having multiple monitors

The max height of a chrome extension is [600px](https://stackoverflow.com/a/6904830/623546)
This chrome/CSS bug happens when a clicking a button below 350px from a window on a secondary monitor.

I will be filling another chrome bug - there isn't much i can do here since this is a native CSS issue that affects multiple extensions. 

I will close this for now but if I have missed anything, feel free to reopen this :)

**Closed by Mimieam** 2019-11-09 02:31 UTC

**Comment by nstielau** [comment] 2019-11-09 03:00
#hero #probablyChomesFault #opensource #fridaynight #thanks!
