### ISSUE TITLE
tabSorter2 cannot be find in chrome extensions

### ISSUE THREAD

**Issue by xgrommx** [Mimieam/TabSorter2#28] opened 2021-04-17 16:58 UTC
Hi, looks like this extension was removed from chrome store. I don't know what is reason, but this extension was amazing.

**Comment by nyhtml** [comment] 2021-04-25 13:44
I found the same thing happened to me. I was using two extensions until I found [TabSorter2](https://github.com/Mimieam/TabSorter2) and then noticed my option wasn't on the browser anymore. At first, I thought I had turned it off but it is completely gone with no notification. I guess I will have to use those two old extensions again until it returns.

**Comment by DennisLindblom71** [comment] 2021-04-25 15:56
What other extension do you recommend?

**Comment by nyhtml** [comment] 2021-04-25 16:37
I have gone back to pinned "[Merge All Windows](https://chrome.google.com/webstore/detail/merge-windows/mmpokgfcmbkfdeibafoafkiijdbfblfg)" (to merge all my open Chrome windows into one) and then "[Tab Sorter](https://chrome.google.com/webstore/detail/tab-sorter/nlnkcinjjeoojlhdiedbbolilahmnldj)" (which sorts alphabetically by the domain name) so I can look and see which favicon is open the most and close what I no longer need.

I also have "[Tab Count](https://chrome.google.com/webstore/detail/tab-count/cfokcacdaonnckdmopmcgeanhkebeaio)" (to see if I go over 50 tabs) since my laptop only has 8 GB of RAM unlike my Hackintosh with 64 GB of RAM and a benefit is to be able to see the full website title of all the open tab. I don't know if Chrome still supports installs of extensions outside of the store using developer mode so that might be the only way to get TabSorter2 back if it is was dropped.

**Comment by xgrommx** [comment] 2021-04-25 20:23
Together with tabSorter2 I use
https://chrome.google.com/webstore/detail/list-opened-tabs/nkaliaagdnbgadcpnkdbmnigkalbihlb

Now I should use (because deduplicate was my preferable feature in tabSorter2)
https://chrome.google.com/webstore/detail/duplicate-tabs-closer/gnmdbogfankgjepgglmmfmbnimcmcjle

**Comment by xgrommx** [comment] 2021-04-25 20:25
By the way google chrome has already list of opened tabs.

![image](https://user-images.githubusercontent.com/1499594/116008478-727d2a80-a61d-11eb-9151-acbf2874732f.png)

But it still doesn't have count of opened tabs

**Comment by GiovanH** [comment] 2021-04-26 02:45
Hope the web store issue gets sorted out soon.

**Comment by nyhtml** [comment] 2021-04-26 19:42
> By the way google chrome has already a list of opened tabs.

Nice one, @xgrommx! I hadn't seen that before. Google must have snuck it in recently. Whit that baked in, I could now disable my [Peek-A-Tab](https://chrome.google.com/webstore/detail/peek-a-tab-tabs-manager-f/nnpdamdaknpnohmlbnmgphiodghbohop) as that is providing the same function minus the keyboard shortcut. I have to see if that is on the OS X/Mac version as well.
> But it still doesn't have a count of opened tabs

So that means I will still have to go to `chrome://inspect/#pages` and do a `CTRL + F` for the word `inspect` if I want to know the total without using an app/extension until Google finally bakes it in.

**Comment by Mimieam** [comment] 2021-04-27 03:11
Hey Guys! Sorry for the inconvenience,  The extension has been pulled Pending Permissions reviews. 
I'm creating a light version of TS2 that remove the management, download and system.display permissions.
The Save, Split, AutoSorting and stacking functionalities will be affected and likely disabled until suitable workarounds are found :/

**Comment by GiovanH** [comment] 2021-04-28 05:20
That would be a critical regression. What's Google's objection with the current permissions setup? What prompted the change?

**Comment by DennisLindblom71** [comment] 2021-05-07 10:19
How is this problem going?

**Comment by nyhtml** [comment] 2021-05-07 10:28
> How is this problem going?
At least 3 weeks.

**Comment by cduran** [comment] 2021-05-09 17:09
Also found this one https://chrome.google.com/webstore/detail/tab-organizer/kkcbifggchajpkagcpagenpfghbplghc

**Comment by DennisLindblom71** [comment] 2021-05-28 06:54
Any news?

**Comment by xgrommx** [comment] 2021-07-09 04:53
Any updates?

**Comment by FarisHijazi** [comment] 2021-07-15 11:54
Any plans on releasing the source code? even minified, we could at least have a way to download the extension as a developer rather than from the chrome store.

If source code is released I'm more than willing to help out with development too.

**Comment by GiovanH** [comment] 2021-07-20 03:02
If there are no plans to release the source code and the reason for the exclusion is still being kept a secret, that's reason to believe that the extension was actually compromised and @Mimieam has been using it to distribute malware

**Comment by nyhtml** [comment] 2021-07-26 06:31
3 months has passed (Apr25-July25) so I'm moving on, @Mimieam.
Thanks for at least making my online interactions easier while it was around.

**Comment by shawn-yee** [comment] 2021-07-28 07:26
This is an amazing extension.
I hope the author will continue to maintain it.

**Comment by DennisLindblom71** [comment] 2021-09-07 08:13
I really miss this extension so much. I have not found anything that even comes close to this feature. I really hope the developer has not turned off the development. I could easily pay to get it back.

**Comment by GiovanH** [comment] 2021-09-12 20:48
Mirroring the original source here for security research: https://github.com/GiovanH/TabSorter2

**Comment by DennisLindblom71** [comment] 2022-04-05 06:33
When do you think you will release the new version?

**Comment by Mimieam** [comment] 2022-04-08 20:40
> When do you think you will release the new version?

Hi @DennisLindblom71, finding fixed and workaround for core features in MV3 turns out to be a lot more involved than expected. If all goes well, I'm aiming for mid-summer.

Please stay tuned :)

**Comment by Mimieam** [comment] 2022-07-10 04:51
Thank you guys for your patience, I'm closing this issue since [ Ts2 v2.0.0 ](https://chrome.google.com/webstore/detail/tabsorter2/lmmmdnmgmgnimgcfbnomdgeldehlfafn)was released a few days ago. Feel free to start a discussion for questions or feedback :)

**Closed by Mimieam** 2022-07-10 04:51 UTC

**Comment by xgrommx** [comment] 2022-08-20 16:46
@Mimieam are u sure that subscription model for chrome extensions is a good idea?

**Comment by Mimieam** [comment] 2022-08-21 12:45
> @Mimieam are u sure that subscription model for chrome extensions is a good idea?

Hi @xgrommx, that's a great question. The short answer is yes.
 
It is fair to say that it is not typical for a chrome extension to have a subscription model, given that from all paid extensions on chrome only about [5.7%](https://truelist.co/blog/google-chrome-statistics/#:~:text=About%204.7%25%20of%20extensions%20are,extensions%20don't%20require%20payment.) are subscription based. 
I’m aware that most users of extensions not used to paying for them, this is why the basic features/options that I believe most users are expecting from this extension will always be free. 

I enjoy working on this extension and by using a freemium model, I can focus on continuing to improve the extension, and provide more and more awesome features to those supporting my work.  So I think a subscription model is currently a good fit for TabSorter2, and I really hope that anyone finding value in this extension would consider subscribing to support it.

I hope this answer your question, feel free to open a [discussion](https://github.com/Mimieam/TabSorter2/discussions) if you would like to chat more about this 😊


ps: I'm also looking into adding a free trial, and providing different subscription options/discounts.

**Comment by xgrommx** [comment] 2022-08-23 14:26
@Mimieam Sorry, but I'll never to use this extensions anymore and I will don't recommend it someone in feature. It will be reasonable for IDE or smth similar but not for chrome extensions (one-pay model will be possible, but not subscription model)

**Comment by Mimieam** [comment] 2022-08-24 02:48
@xgrommx I'm very sorry you feel that way, thank you for your honest feedback and take care.
